[project]
name = "web-bot-auth"
version = "0.1.0"
description = "A library to check for AI Bot Authentication using the latest HTTP header Signature."
requires-python = ">=3.13"
dependencies = [
    "wheel"
]

[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"