name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Pick a Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3. Install `uv`
      - name: Install uv
        run: python -m pip install --upgrade pip && pip install uv

      # 4. Sync dependencies (uses your lock file)
      - name: Sync dependencies
        run: uv sync

      # 5. Build the package
      - name: Build package
        run: uv build --no-sources

      # 6. Run all examples under examples/foo
      - name: Run examples
        run: |
          for example in examples/*; do
            echo "Running $example"
            cd "$example"
            uv run main.py
          done
