name: Publish Python 🐍 distribution 📦 to PyPI and TestPyPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build distribution 📦
    runs-on: ubuntu-latest

    steps:
      # 1. Grab your repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Pick a Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 3. Install `uv`
      - name: Install uv
        run: python -m pip install --upgrade pip && pip install uv

      # 4. Sync dependencies (uses your lock file)
      - name: Sync dependencies
        run: uv sync

      # 5. Build the package
      - name: Build package
        run: uv build --no-sources

      # 6. Lint
      - name: Lint
        run: |
          uv run ruff check .
          uv run black --check .

      # 7. Run all examples under examples/foo
      - name: Run examples
        run: |
          echo "Running crawl4ai"
          cd examples/crawl4ai-hook
          uv run playwright install --with-deps chromium
          uv run main.py

          echo "Running scrapy-spider"
          cd ../scrapy-spider
          uv pip install -e .
          uv run scrapy runspider main.py

      # 8. Store dist for publishing job
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish-to-pipy:
    name: Publish Python 🐍 distribution 📦 to PyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/bot-auth
    permissions:
      id-token: write
    steps:
      # 1. Get the dist artifact
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      # 2. Publish to PyPI
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-to-testpipy:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/bot-auth
    permissions:
      id-token: write
    steps:
      # 1. Get the dist artifact
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
            name: python-package-distributions
            path: dist/

      # 2. Publish to TestPyPI
      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/